var whiskeyData = 
[
  [
    "name",
    "price",
    "location",
    "year",
    "icon",
    "abv",
    "peaty",
    "smoky",
    "sweet",
    "savoury",
    "peaty icon",
    "smoky icon",
    "sweet icon",
    "savoury icon"
  ],
  [
    "Aberlour 10-year-old",
    49.49,
    "Speyside",
    10,
    "cinnamon, raisins, honey,malt",
    "40%",
    0,
    1,
    9,
    0,
    "",
    "",
    "cinnamon, raisins, malt",
    ""
  ],
  [
    "Aberlour 12-year-old double cask Matured",
    59.25,
    "Speyside",
    12,
    "cinnamon, raisins, dark chocolate, toffee, plums",
    "48%",
    0,
    2,
    8,
    0,
    "",
    "",
    "cinnamon, raisins, dark chocolate, toffee, plums",
    ""
  ],
  [
    "Aberlour 15-year-old Select Cask Reserve",
    68.5,
    "Speyside",
    15,
    "toffee, plums, mint",
    "43%",
    0,
    1,
    9,
    0,
    "",
    "",
    "toffee, plums, mint",
    ""
  ],
  [
    "Aberlour 16-year-old Double Cask Matured",
    115.36,
    "Speyside",
    16,
    "cinnamon, raisins, milk chocolate, toffee",
    "40%",
    0,
    1,
    9,
    0,
    "",
    "",
    "cinnamon, raisins, milk chocolate, toffee",
    ""
  ],
  [
    "Aberlour 18-year-old Sherry Wood Matured",
    128,
    "Speyside",
    18,
    "cinnamon, raisins, doughnuts, black pepper",
    "43%",
    2,
    0,
    8,
    0,
    "black pepper",
    "",
    "cinnamon, raisins",
    ""
  ],
  [
    "Aberlour a'bunadh ('The Origin')",
    132.99,
    "Speyside",
    22,
    "cinnamon, raisins, sherry, dark chocolate, dried fruits, blackcurrant",
    "60.80%",
    0,
    2,
    7,
    1,
    "",
    "",
    "cinnamon, raisins, sherry, dark chocolate",
    ""
  ],
  [
    "Ardbeg 10-year-old",
    69.29,
    "Islay",
    10,
    "liquorice root, smoke, tobacco, coffee, meat",
    "46%",
    0,
    5,
    4,
    1,
    "",
    "smoke, tobacco, coffee",
    "liquorice root",
    "meat"
  ],
  [
    "Ardbeg 17-year-old",
    1999,
    "Islay",
    17,
    "liquorice root, smoke, tobacco, coffee",
    "40%",
    0,
    5,
    5,
    0,
    "",
    "smoke, tobacco, coffee",
    "liquorice root",
    ""
  ],
  [
    "Ardbeg Auriverdes",
    499,
    "Islay",
    10,
    "tropical fruits, cream, smoke, peat",
    "49.90%",
    2,
    2,
    6,
    0,
    "peat",
    "smoke",
    "tropical fruits, cream",
    ""
  ],
  [
    "Ardbeg Blasda",
    253.85,
    "Islay",
    15,
    "smoke, fruits",
    "40%",
    0,
    5,
    5,
    0,
    "",
    "smoke",
    "fruits",
    ""
  ],
  [
    "Ardbeg Corryvreckan",
    103.81,
    "Islay",
    30,
    "white pepper, anise(star), cherry, smoke coffeee, meat",
    "57.10%",
    1,
    4,
    1,
    4,
    "white pepper",
    "smoke, coffee",
    "cherry",
    "anise(star),meat"
  ],
  [
    "Ardbeg Kelpie",
    699,
    "Islay",
    10,
    "meat, spice, toffee, dark chocolate, fruits",
    "46%",
    2,
    0,
    6,
    2,
    "spice",
    "",
    "toffee, dark chocolate, fruits",
    "meat"
  ],
  [
    "Ardbeg Supernova",
    414.62,
    "Islay",
    5,
    "liquorice root, cocoa",
    "58.90%",
    0,
    4,
    6,
    0,
    "",
    "cocoa",
    "liquorice root",
    ""
  ],
  [
    "Bruichladdich 21-year-old",
    1194,
    "Islay",
    21,
    "dried fruits, orange fruit-candy",
    "46%",
    0,
    0,
    10,
    0,
    "",
    "",
    "dried fruits, orange fruit, candy",
    ""
  ],
  [
    "Bruichladdich Black Art 5",
    347,
    "Islay",
    26,
    "vanilla, ginger, raisins, apple, blackberry, plums",
    "48.40%",
    0,
    0,
    10,
    0,
    "",
    "",
    "vanilla, ginger, raisins, apple, blackberry, plums",
    ""
  ],
  [
    "Bruichladdich Blacker Still",
    1549,
    "Islay",
    26,
    "prune, sultanas, ginger",
    "50.70%",
    0,
    2,
    8,
    0,
    "",
    "",
    "sultanas, ginger",
    ""
  ],
  [
    "Bruichladdich Infinity",
    205,
    "Islay",
    5,
    "chocolate, dried fruits, honey, new woood, sherry",
    "52.50%",
    0,
    0,
    6,
    4,
    "",
    "",
    "chocolate, dried fruits, honey, sherry",
    "new wood"
  ],
  [
    "Bruichladdich Islay Barely",
    82.11,
    "Islay",
    6,
    "lemon, apple, peach",
    "50%",
    0,
    0,
    10,
    0,
    "",
    "",
    "lemon, apple, peach",
    ""
  ],
  [
    "Bruichladdich Octomore",
    179,
    "Islay",
    30,
    "chocolate, dried fruits, honey, leave, hazelnut",
    "63.50%",
    0,
    0,
    8,
    2,
    "",
    "",
    "chocolate, dried fruits, honey",
    "leaves, hazelnut"
  ],
  [
    "Bruichladdich The Classic Laddies Scottish Barley",
    96,
    "Islay",
    0,
    "cinnamon, peach, salt, smoke, cream",
    "50%",
    1,
    1,
    7,
    1,
    "salt",
    "smoke",
    "cinnamon, peach,cream",
    ""
  ],
  [
    "Glen Garioch Founders's Reserve",
    57.75,
    "Highlands",
    10,
    "honey, malt, biscuits, oak",
    "48%",
    0,
    0,
    5,
    5,
    "",
    "",
    "honey, malt, biscuits",
    "oak"
  ],
  [
    "Glen Garioch Virgin Oak",
    114.55,
    "Highlands",
    10,
    "toasted oakiness, vanilla, black pepper",
    "48%",
    3,
    3,
    4,
    0,
    "black pepper",
    "toasted oak",
    "vanilla",
    ""
  ],
  [
    "Glenfarclas 10-year-old",
    54.3,
    "Speyside",
    10,
    "cinnamon, raisins, honey, malt",
    "40%",
    0,
    0,
    9,
    1,
    "",
    "",
    "cinnamon, raisins, honey, malt",
    ""
  ],
  [
    "Glenfarclas 12-year-old",
    65.93,
    "Speyside",
    12,
    "nutmeg, cinnamon, raisins, apple, honey",
    "43%",
    0,
    0,
    9,
    1,
    "",
    "",
    "cinnamon, raisins, apple, honey",
    "nutmeg"
  ],
  [
    "Glenfarclas 15-year-old",
    87.3,
    "Speyside",
    15,
    "cinnamon, sherry, smoke, malt, butter, grape",
    "46%",
    0,
    3,
    6,
    1,
    "",
    "smoke",
    "cinnamon, sherry, malt, grape",
    "butter"
  ],
  [
    "Glenfarclas 21-year-old",
    149,
    "Speyside",
    21,
    "vanilla, smoke, malt, honey",
    "43%",
    0,
    3,
    7,
    0,
    "",
    "smoke",
    "vanilla,malt, honey",
    ""
  ],
  [
    "Glenfarclas 25-year-old",
    189,
    "Speyside",
    25,
    "sherry, fruit cake, hazenuts, dark chocolate, coffeee",
    "43%",
    0,
    0,
    6,
    3,
    "",
    "",
    "sherry, fruit cake",
    "hazelnut"
  ],
  [
    "Glenfarclas 30-year-old",
    589,
    "Speyside",
    30,
    "marzipan, icing, coffeee, burnt chocolate",
    "43%",
    0,
    6,
    2,
    2,
    "",
    "coffee, burnt chocolate",
    "icing",
    "marzipan"
  ],
  [
    "Glenfarclas 40-year-old",
    1287.27,
    "Speyside",
    40,
    "black pepper, orange fruit, raspberry, milk chocolate",
    "46%",
    4,
    0,
    6,
    0,
    "black pepper",
    "",
    "orange fruit, raspberry, milk chocolate",
    ""
  ],
  [
    "Glenfiddich 125th Anniversary Edition",
    216,
    "Speyside",
    20,
    "smoke, oak, sherry, dried fruits",
    "43%",
    0,
    4,
    5,
    1,
    "",
    "smoke",
    "sherry, dried fruits",
    "oak"
  ],
  [
    "Glenfiddich 12-year-old",
    59.99,
    "Speyside",
    12,
    "vanilla, pear, apple, cream",
    "40%",
    0,
    0,
    10,
    0,
    "",
    "",
    "vanilla, pear, apple, cream",
    ""
  ],
  [
    "Glenfiddich 15-year-old",
    64.21,
    "Speyside",
    15,
    "ginger, cinnamon, sherry, marzipan, oak",
    "40%",
    0,
    0,
    6,
    4,
    "",
    "",
    "ginger, cinnamon, sherry",
    "marzipan,oak"
  ],
  [
    "Glenfiddich 18-year-old",
    139.99,
    "Speyside",
    21,
    "raisins, plums, apricots, grape",
    "40%",
    0,
    0,
    10,
    0,
    "",
    "",
    "raisins, plums, apricots, grape",
    ""
  ],
  [
    "Glenfiddich 21-year-old",
    244.99,
    "Speyside",
    21,
    "apple, rum, oak, butterscotch, dried fruits",
    "40%",
    0,
    1,
    7,
    2,
    "",
    "",
    "apple, dark rum, dried fruits",
    "oak"
  ],
  [
    "Glenfiddich 50-year-old",
    3499,
    "Speyside",
    50,
    "orange fruit, grapefruits, honey",
    "46.10%",
    0,
    0,
    10,
    0,
    "",
    "",
    "orange fruit, grape, honey",
    ""
  ],
  [
    "Glenfiddich Age of Discovery Bourbon 19-year-old",
    164.87,
    "Speyside",
    19,
    "tropical fruits, sweetness, spices",
    "40%",
    3,
    0,
    7,
    0,
    "spice",
    "",
    "tropical fruits",
    ""
  ],
  [
    "Glenmorangie 18-year-old",
    120.3,
    "Highlands",
    18,
    "orange fruit, graperfruits, honey, malt, cream",
    "43%",
    0,
    2,
    6,
    2,
    "",
    "",
    "orange fruit, grape, honey, malt, cream",
    ""
  ],
  [
    "Glenmorangie 25-year-old",
    502.27,
    "Highlands",
    25,
    "honey, oak, spice, orange fruit, stewed fruits",
    "43%",
    2,
    0,
    3,
    5,
    "spice",
    "",
    "honey,orange fruit",
    "stewed fruits, oak"
  ],
  [
    "Glenmorangie Astar",
    115.36,
    "Highlands",
    11,
    "Vanilla, Lemon, Almond, Coconut, Honey, Oak",
    "52.50%",
    0,
    0,
    7,
    3,
    "",
    "",
    "vanilla, lemon, coconut, honey",
    "oak, almond"
  ],
  [
    "Glenmorangie Milsean",
    184.99,
    "Highlands",
    12,
    "cherry, mango, tropical fruits, grape",
    "40%",
    0,
    0,
    10,
    0,
    "",
    "",
    "cherry, mango, tropical fruits, grape",
    ""
  ],
  [
    "Glenmorangie Nectar d'Or",
    84.01,
    "Highlands",
    12,
    "Ginger, Nutmeg, Lemon, Honey ",
    "46%",
    0,
    0,
    7,
    3,
    "",
    "",
    "ginger, lemon, honey",
    "nutmeg"
  ],
  [
    "Glenmorangie Original",
    69.99,
    "Highlands",
    10,
    "Lemon, Apricot, Honey, Malt, Toffee",
    "40%",
    0,
    0,
    9,
    1,
    "",
    "",
    "lemon, honey, malt, toffee",
    ""
  ],
  [
    "Glenmorangie Quinta Ruban",
    74.11,
    "Highlands",
    12,
    "Nutmeg, Raisins, orange fruit, Port, Walnut, Dark chocolate",
    "46%",
    0,
    0,
    6,
    4,
    "",
    "",
    "raisins, orange fruit, dark chocolate",
    "nutmeg, walnut"
  ],
  [
    "Highland Park 12-year-old",
    92.71,
    "Islands",
    12,
    "Heather, Brine, Smoke, Honey ",
    "40%",
    0,
    4,
    3,
    3,
    "",
    "smoke",
    "honey",
    "brine"
  ],
  [
    "Highland Park 15-year-old",
    140,
    "Islands",
    15,
    "malt, toffee, oak, smoke",
    "40%",
    0,
    4,
    2,
    4,
    "",
    "smoke",
    "malt, toffee",
    "oak"
  ],
  [
    "Highland Park 16-year-old",
    154.63,
    "Islands",
    16,
    "orange fruit, honey, orange fruit, candy, smoke",
    "40%",
    0,
    5,
    5,
    0,
    "",
    "smoke",
    "orange fruit, honey, orange fruit, candy",
    ""
  ],
  [
    "Highland Park 18-year-old",
    268.14,
    "Islands",
    18,
    "Smoke, Honey, Toffee, Stewed fruits",
    "43%",
    0,
    4,
    4,
    2,
    "",
    "smoke",
    "honey, toffee",
    "stewed fruits"
  ],
  [
    "Highland Park 21-year-old",
    299.1,
    "Islands",
    21,
    "malt, oak, honey",
    "43%",
    0,
    0,
    5,
    5,
    "",
    "",
    "honey, malt",
    "oak"
  ],
  [
    "Highland Park 25-year-old",
    412.58,
    "Islands",
    25,
    "lemon, grape, honey, candy, orange fruit",
    "53.50%",
    0,
    0,
    10,
    0,
    "",
    "",
    "lemon, grape, honey, candy, orange fruit",
    ""
  ],
  [
    "Highland Park 30-year-old",
    957.04,
    "Islands",
    30,
    " Force 9 flavour toffee, dark chocolate orange fruit and hobbister hill peat",
    "48.10%",
    4,
    0,
    6,
    0,
    "peat",
    "",
    "toffee, dark chocolate, orange fruit",
    ""
  ],
  [
    "Lagavulin 12-year-old Cask Strength",
    164.95,
    "Islay",
    12,
    "Leaves, Mint, orange fruit, Lime, Brine, Smoke",
    "57.80%",
    0,
    2,
    4,
    4,
    "",
    "smoke",
    "orange fruit, lime,",
    "leaves, brine "
  ],
  [
    "Lagavulin 16-year-old",
    80.78,
    "Islay",
    16,
    "orange fruit, Pineapple, Brine, Kippers, Smoke",
    "43%",
    0,
    2,
    5,
    3,
    "",
    "smoke",
    "orange fruit, pineapple",
    "skippers"
  ],
  [
    "Lagavulin Then Distillers's Edition",
    134.09,
    "Islay",
    20,
    "Vanilla, Raisins, Iodine (tcp), Tar, coffeee",
    "43%",
    3,
    3,
    4,
    0,
    "TCP",
    "tar, coffee",
    "vanilla, raisins",
    ""
  ],
  [
    "Laphroaig 10-year-old",
    55.95,
    "Islay",
    10,
    "peaty, smoke, tobacco",
    "55.70%",
    4,
    6,
    0,
    0,
    "peat",
    "smoke, tobacco",
    "",
    ""
  ],
  [
    "Laphroaig 10-year-old Cask Strength",
    263.97,
    "Islay",
    10,
    "peaty, pepper, smoke",
    "55.30%",
    6,
    4,
    0,
    0,
    "peat, black pepper",
    "smoke",
    "",
    ""
  ],
  [
    "Laphroaig 18-year-old",
    339.67,
    "Islay",
    18,
    "liquorice root,  hickory",
    "48%",
    0,
    0,
    5,
    5,
    "",
    "",
    "liquorice root",
    "walnut"
  ],
  [
    "Laphroaig 25-year-old",
    618.8,
    "Islay",
    25,
    "liquorice root, tobacco, smoke, meat",
    "48.60%",
    0,
    4,
    3,
    3,
    "",
    "tobacco, smoke",
    "liquorice root",
    "meat"
  ],
  [
    "Laphroaig 30-year-old",
    1799,
    "Islay",
    30,
    "Vanilla, orange fruit, Peach, Tobacco, Pencil shavings, Plums",
    "53.50%",
    0,
    0,
    6,
    4,
    "",
    "",
    "vanilla, orange fruit, peach, plums",
    "pencil shavings"
  ],
  [
    "Laphroaig Quarter Cask",
    60.64,
    "Islay",
    12,
    "Smoke, Dark Chocolate, Malt, Tobacco, Toffee",
    "48%",
    0,
    5,
    5,
    0,
    "",
    "smoke, tobacco",
    "dark chocolate, malt,toffee",
    ""
  ],
  [
    "Talisker 10-year-old",
    60.88,
    "Islands",
    10,
    "Heather, White Pepper, Brine, Smoke, Malt",
    "45.80%",
    2,
    2,
    4,
    2,
    "white pepper",
    "smoke",
    "toffee, malt",
    "brine"
  ],
  [
    "Talisker 18-year-old",
    126.17,
    "Islands",
    18,
    "orange fruit, Brine, Tar, Smoke, Toffee",
    "45.80%",
    0,
    4,
    5,
    1,
    "",
    "tar, smoke",
    "orange fruit, toffee",
    "brine"
  ],
  [
    "Talisker 25-year-old",
    399,
    "Islands",
    25,
    "Black Pepper, Clove, Smoke, Toast",
    "45.80%",
    3,
    3,
    0,
    4,
    "black pepper",
    "smoke, toasted oak",
    "",
    "clove"
  ],
  [
    "Talisker 30-year-old",
    675,
    "Islands",
    30,
    "seaweed, smoke, toast, coffee",
    "45.80%",
    0,
    7,
    0,
    3,
    "",
    "toasted coffee, smoke",
    "",
    "seaweed"
  ],
  [
    "Talisker 57 North",
    115.36,
    "Islands",
    12,
    "Black Pepper, Seaweed, Smoke, Toffee",
    "57%",
    2,
    6,
    1,
    1,
    "black pepper",
    "toasted coffee, smoke",
    "orange fruit",
    "seaweed"
  ],
  [
    "Talisker Dark Storm",
    78.99,
    "Islands",
    10,
    "tobacco, coffee, taosted coffee, smoke, orange fruit",
    "45.80%",
    0,
    8,
    2,
    0,
    "",
    "tobacco, coffee, toasted coffee, smoke",
    "orange fruit",
    ""
  ],
  [
    "Talisker Storm",
    79.9,
    "Islands",
    10,
    "White Pepper, orange fruit, Brine, Smoke, Oak, Stewed fruits",
    "45.80%",
    4,
    1,
    0,
    5,
    "white pepper",
    "smoke",
    "",
    " oak, stewed fruits,brine"
  ],
  [
    "Talisker The Distiller's Edition",
    102,
    "Islands",
    12,
    "Black pepper, smoke, coffee",
    "45.80%",
    4,
    6,
    0,
    0,
    "black pepper",
    "smoke, coffee",
    "orange fruit",
    ""
  ],
  [
    "The Balvenie DoubleWood 12-year-old",
    94.99,
    "Speyside",
    12,
    "black pepper, cinnamon, raspberry, milk chocolate, stewed fruits",
    "40%",
    1,
    0,
    5,
    4,
    "black pepper",
    "",
    "cinnamon, raspberry, milk chocolate",
    " stewed fruits"
  ],
  [
    "The Balvenie DoubleWood 17-year-old",
    148.37,
    "Speyside",
    17,
    "vanilla, cinnamon, mango, milk chocolate, cream, christmas cake",
    "43%",
    0,
    1,
    9,
    0,
    "",
    "",
    "vanilla, cinnamon, mango, milk chocolate, cream",
    ""
  ],
  [
    "The Balvenie PortWood 21-year-old",
    219.33,
    "Speyside",
    21,
    "cinnamon, raisins, orange fruit, hazelnut, honey, cream",
    "43%",
    0,
    0,
    9,
    1,
    "",
    "",
    "cinnamon, raisins, orange fruit, honey, cream",
    "hazelnut"
  ],
  [
    "The Balvenie RumCask 17-year-old",
    710.77,
    "Speyside",
    17,
    "apple, orange fruit, dark rum, raisin",
    "43%",
    0,
    2,
    7,
    1,
    "",
    "",
    "apple, orange fruit, raisins",
    ""
  ],
  [
    "The Balvenie Signature 12-year-old",
    94.99,
    "Speyside",
    12,
    "black pepper, cinnamon, raspberry, milk chocolate, stewed fruits",
    "40%",
    1,
    0,
    7,
    2,
    "black pepper",
    "",
    "cinnamon, raspberry, milk chocolate",
    "stewed fruits"
  ],
  [
    "The Balvenie Single Barrel 15-year old",
    143.5,
    "Speyside",
    15,
    "vanilla, black pepper, oak base",
    "47.80%",
    3,
    0,
    4,
    3,
    "black pepper",
    "",
    "vanilla",
    "oak"
  ],
  [
    "The Balvenie Tun 1509 B4",
    169.99,
    "Speyside",
    26,
    "cinnamon, toasted oka, dark chocolate, doughnuts, ginger,spice",
    "51.70%",
    2,
    2,
    6,
    0,
    "spice",
    "toasted oak",
    "cinnamon, dark chocolate, ginger",
    ""
  ],
  [
    "The Glenlivet 12-year-old",
    65.99,
    "Speyside",
    12,
    "vanilla, lemon, toffee, honey",
    "40%",
    0,
    0,
    8,
    2,
    "",
    "",
    "vanilla, lemon, toffee, honey",
    ""
  ],
  [
    "The Glenlivet 15-year-old French Oak Reserve",
    89.1,
    "Speyside",
    15,
    "almond, butter, dried fruits",
    "40%",
    0,
    0,
    7,
    3,
    "",
    "",
    "dried fruits",
    "almond, butter"
  ],
  [
    "The Glenlivet 18-year-old",
    119,
    "Speyside",
    18,
    "nutmeg, clove, raisins, orange fruit, honey, malt",
    "43%",
    0,
    0,
    5,
    5,
    "",
    "",
    "raisins, orange fruit, honey, malt",
    "nutmeg, clove"
  ],
  [
    "The Glenlivet 21-year-old",
    329.9,
    "Speyside",
    21,
    "beet guts, malt, orange fruit, oak",
    "43%",
    0,
    0,
    6,
    4,
    "",
    "",
    "beetroot,malt, orange fruit",
    "oak "
  ],
  [
    "The Glenlivet Nadurra 16-year-old",
    108,
    "Speyside",
    16,
    "vanilla, pear, apple, smoke",
    "48%",
    0,
    4,
    6,
    0,
    "",
    "smoke",
    "vanilla, pear, apple",
    ""
  ],
  [
    "The Glenlivet XXV",
    502.27,
    "Speyside",
    25,
    "toffee, vanilla,, trademark fruits, oak ",
    "43%",
    0,
    0,
    6,
    4,
    "",
    "",
    "toffee, vanilla, fruits",
    "oak "
  ]
]